biolib_version: 2
modules:
    main:
        image: 'local-docker://esm-fold:latest'
        command: python3 root.py
        working_directory: /home/biolib/
        input_files:
            - COPY / /home/biolib/
        output_files:
            - COPY /home/biolib/output/ /
        gpu: required
main_output_file: /output.md
arguments:
    -
        key: '--fasta-file'
        key_value_separator: ' '
        default_value: ''
        description: 'Input FASTA file'
        required: true
        type: text-file
